name: Build Native

on: [push, pull_request, release]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'liberica'
          cache: maven
      - name: Build native image using Maven
        run: ./mvnw package -Dnative
      - name: Rename output binary for clarity (opsional)
        run: |
          mkdir dist
          mv target/*-runner dist/myapp  # Ganti `myapp` sesuai nama app kamu

      - name: Upload artifact (binary) to GitHub Releases
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          files: dist/myapp
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
